# TODO: Add lnd or core-lightning container.
# TODO: Finish the bookmarks project.
# The nextjs container provides:
# - GPT TRAINER UI
# - LND NETWORK MANAGEMENT UI [TODO]
# - System status overview [TODO]

services:
  wordpress: ## Wordpress CMS
    image: wordpress:6.7.1
    restart: always
    ports:
      - "1000:80" 
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://home.ideniox.com');
        define('WP_SITEURL', 'https://home.ideniox.com');
    depends_on:
      - mysql
    volumes:
      - ./volumes/wordpress:/var/www/html

  mysql: ## DB for wordpress
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  mariadb: ## DB for nextcloud
    image: mariadb:10.6.20
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud: ## Nextcloud PHP CMS
    image: nextcloud:30.0.4
    restart: always
    ports:
      - 1001:80
    links:
      - mariadb
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - /var/www/.well_known:/var/www/.well_known
    environment:
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./volumes/redis:/data
  bookmarks: ## A customiced view in nextjs involving GPT lightning network and Nextcloud Forms to create views
    image: jorgemartinezpizarro/bookmarks:latest
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - NEXT_PUBLIC_NEXTCLOUD_URL=${NEXT_PUBLIC_NEXTCLOUD_URL}
      - PORT=${PORT}
  