# TODO: Add lnd or core-lightning container
# TODO: Add my custom yet private nextjs container
# The nextjs container provides:
# - GPT TRAINER UI
# - LND NETWORK MANAGEMENT UI [TODO]
# - System status overview
services:
  wordpress:
    image: wordpress:6.7.1
    restart: always
    ports:
      - 1000:80
    volumes:
      - ./volumes/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mysql:8.3.0
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  db:
    image: mariadb:10.6.20
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud:
    image: nextcloud:30.0.4
    restart: always
    ports:
      - 1001:80
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - /var/www/.well_known:/var/www/.well_known
    environment:
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./volumes/redis:/data